name: Yanzz SSH Telegram

on:
  workflow_dispatch:
    inputs:
      os:
        description: 'Choose OS: ubuntu-latest or debian-10'
        required: true
        default: 'ubuntu-latest'
        type: choice
        options:
          - ubuntu-latest
          - debian-10

jobs:
  ssh-telegram:
    runs-on: ${{ github.event.inputs.os }}
    timeout-minutes: 4320  # 3 hari

    steps:
      - name: Cache apt packages
        uses: actions/cache@v3
        with:
          path: /var/cache/apt/archives
          key: ${{ runner.os }}-apt-cache

      - name: Update & Install Packages
        run: |
          sudo apt-get update -y
          sudo apt-get install -y openssh-server curl sudo || true
          sudo systemctl enable ssh
          sudo systemctl start ssh

      - name: Create SSH User
        run: |
          USERNAME="yanzz"
          PASSWORD=$(openssl rand -base64 12)

          if id "$USERNAME" >/dev/null 2>&1; then
            sudo deluser --remove-home $USERNAME
          fi

          sudo adduser --disabled-password --gecos "" $USERNAME
          echo "$USERNAME:$PASSWORD" | sudo chpasswd
          sudo usermod -aG sudo $USERNAME

          echo "SSH_USERNAME=$USERNAME" >> $GITHUB_ENV
          echo "SSH_PASSWORD=$PASSWORD" >> $GITHUB_ENV

      - name: Install & Configure Tailscale
        run: |
          curl -fsSL https://tailscale.com/install.sh | sh
          # background reconnect
          while true; do
            if ! tailscale status >/dev/null 2>&1; then
              echo "Tailscale not connected. Reconnecting..."
              sudo tailscale up --authkey=${{ secrets.TAILSCALE_AUTH_KEY }} --hostname=gh-runner-$GITHUB_RUN_ID || true
            fi
            sleep 60
          done &

      - name: Get Tailscale IP
        run: |
          sleep 5
          TAILSCALE_IP=$(tailscale ip -4)
          echo "TAILSCALE_IP=$TAILSCALE_IP" >> $GITHUB_ENV

      - name: Send SSH Info to Telegram
        run: |
          MESSAGE="================== SSH ACCESS ==================
OS: ${{ github.event.inputs.os }}
IP: $TAILSCALE_IP
Username: $SSH_USERNAME
Password: $SSH_PASSWORD
================================================"

          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
            -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
            -d text="$MESSAGE"

      - name: Keep SSH Active
        run: |
          while true; do
            echo "[$(date)] SSH active via Tailscale"
            sleep 300
          done
