name: Yanzz SSH Quick Start

on:
  workflow_dispatch:
    inputs:
      os:
        description: 'Choose OS: ubuntu-latest or debian-10'
        required: true
        default: 'ubuntu-latest'
        type: choice
        options:
          - ubuntu-latest
          - debian-10

jobs:
  quick-ssh:
    runs-on: ${{ github.event.inputs.os }}
    timeout-minutes: 4320  # 3 hari

    steps:
      - name: Cache apt packages
        uses: actions/cache@v3
        with:
          path: /var/cache/apt/archives
          key: ${{ runner.os }}-apt-cache

      - name: Update & Install Required Packages
        run: |
          sudo apt-get update -y
          sudo apt-get install -y openssh-server curl sudo || true

          # Enable SSH service
          sudo systemctl enable ssh
          sudo systemctl start ssh

      - name: Create SSH User
        run: |
          USERNAME="yanzz"
          PASSWORD=$(openssl rand -base64 12)

          if id "$USERNAME" >/dev/null 2>&1; then
            sudo deluser --remove-home $USERNAME
          fi

          sudo adduser --disabled-password --gecos "" $USERNAME
          echo "$USERNAME:$PASSWORD" | sudo chpasswd
          sudo usermod -aG sudo $USERNAME

          echo "SSH_CREDS=User: $USERNAME | Password: $PASSWORD" >> $GITHUB_ENV

      - name: Install & Configure Tailscale
        run: |
          curl -fsSL https://tailscale.com/install.sh | sh

          # Background loop untuk reconnect otomatis Tailscale
          while true; do
            if ! tailscale status >/dev/null 2>&1; then
              echo "Tailscale not connected. Reconnecting..."
              sudo tailscale up --authkey=${{ secrets.TAILSCALE_AUTH_KEY }} --hostname=gh-runner-$GITHUB_RUN_ID || true
            fi
            sleep 60
          done &

      - name: Get Tailscale IP
        run: |
          sleep 5
          TAILSCALE_IP=$(tailscale ip -4)
          echo "TAILSCALE_IP=$TAILSCALE_IP" >> $GITHUB_ENV
          echo "Tailscale IP: $TAILSCALE_IP"

      - name: Display SSH Info
        run: |
          echo "================== SSH ACCESS =================="
          echo "OS: ${{ github.event.inputs.os }}"
          echo "IP: ${{ env.TAILSCALE_IP }}"
          echo "Username: yanzz"
          echo "Password: $(echo ${{ env.SSH_CREDS }})"
          echo "================================================"

      - name: Keep SSH Active
        run: |
          while true; do
            echo "[$(date)] SSH active via Tailscale"
            sleep 300
          done
